
# divide builds into “jobs”.
matrix:

# run different languages in one .travis.yml file
include:

#JOB 1: Backend
- language: java

env:
  SPRING_DATASOURCE_URL=jdbc:postgresql://ec2-23-21-244-254.compute-1.amazonaws.com:5432/dcfa13rb5qfhb0?user=faobbeheumttch&password=d6868b4e2c2de8884f98caf9495f1d3672a37a47b060e8217a4a5834e1dc3925&sslmode=require
    
before_install: 
  - chmod +x gradlew
script:
  - ./gradlew build

# deploy:
#  provider: heroku
#  api_key:
#    secure: abbd43ef-e17e-466a-92cb-68e03e2affeb
#  app: cooperator-backend-0000
#  on:
#    repo: McGill-ECSE321-Winter2019/ecse321-group-project-04


#JOB 2 FRONTEND
# - language: node_js
#   node_js:
#   - "6"

# before_install:
#   - cd Frontend
#   - npm install

# script:
#   - npm run build

# deploy:
#  provider: heroku
#  api_key:
#    secure: a7f85a30-34cf-420c-9409-2f289506a89b
#  app: cooperator-frontend-0000
#  on:
#    repo: McGill-ECSE321-Winter2019/ecse321-group-project-04/Frontend